---
# vim: sts=2:sw=2:et
- hosts: perrin
  gather_facts: no
  tasks:
    - command: docker pull mildred/nginx
    - command: docker pull mildred/fpmbot
    - shell: (docker stop fpmbot fpmbot-nginx; docker rm fpmbot fpmbot-nginx; true)
    - command: docker run -d --restart=always
        -v /var/log/fpmbot:/var/log/fpmbot
        -v /var/lib/fpmbot:/var/lib/fpmbot
        --name=fpmbot
        mildred/fpmbot
    - command: docker run -d --restart=always
        -v /var/lib/fpmbot/web:/usr/share/nginx/html:ro
        --name=fpmbot-nginx
        -e AUTOINDEX=ON
        mildred/nginx
# Follow by haproxy

