---
# vim: sts=2:sw=2:et
- hosts: perrin
  gather_facts: no
  tasks:
    - shell: (docker stop mildred-web; docker rm mildred-web; true)
    - command: docker run -d --restart=always
        --name=mildred-web
        --link=mildred-roundcube:mail
        --link=fpmbot-nginx:files
        -p 80:80 -p 443:443
        -e DOMAIN=mildred.fr
        -e MAIL_PORT_443_DISABLE=true
        -v /etc/ssl/web:/etc/ssl/web
        haproxy

