---
- git:  repo=https://github.com/mildred/backup-next.git
        dest=/usr/local/src/backup-next
- command: cp /usr/local/src/backup-next/backup /usr/local/bin/backup
- command: mkdir -p /usr/local/share/backup/
- command: rm -rf /usr/local/share/backup/drivers
- command: cp -r /usr/local/src/backup-next/drivers /usr/local/share/backup/drivers

- apt: name=rdiff-backup state=present
- apt: name=duplicity    state=present
- apt: name=ncftp        state=present
- file: dest='/etc/backup.d/driver' src='/usr/local/share/backup/drivers/duplicity' state=link
- file: path='/etc/backup.d' state=directory
- file: path='/backup-test' state=directory
- copy:
    dest: /etc/backup.d/rdiff-backup.conf
    content: |
      DESTINATION=/backup-test
      AUTO_PRUNE=true
      AUTO_PRUNE_DELAY=1W

- copy:
    dest: /etc/backup.d/duplicity.conf
    mode: 0600
    content: |
      DESTINATION=ftp://sd-43505@dedibackup-dc2.online.net/perrin-duplicity
      AUTO_PRUNE=true
      AUTO_PRUNE_DELAY=1W
      
      export FTP_PASSWORD='{{ lookup('password', playbook_dir + '/credentials/perrin/backup.ftppass length=15') }}'
      export PASSPHRASE='{{ lookup('password', playbook_dir + '/credentials/perrin/backup.gpgpass length=30') }}'
      
      FLAGS=(--gpg-options "--compress-algo=bzip2 --bzip2-compress-level=9 --cipher-algo=aes256 --digest-algo=sha512")
      
- copy:
    dest: /etc/systemd/system/backup.timer
    content: |
      [Unit]
      Description=Run backups

      [Timer]
      OnCalendar=daily
      Persistent=true

      [Install]
      WantedBy=timers.target

- copy:
    dest: /etc/systemd/system/backup.service
    content: |
      [Unit]
      Description=Run backups

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/backup backup /etc/backup.d/

- command: systemctl enable backup.timer
