---
- user: name='{{user}}' generate_ssh_key=yes
  register: u
- command: cat "{{u.home}}/.ssh/id_rsa.pub"
  register: pubkey
- authorized_key: key="{{pubkey.stdout}}" user='{{user}}'
#- authorized_key: key="{{ remote('file', u.home + '/.ssh/id_rsa.pub') }}" user='{{user}}'
- copy:
    dest: /etc/systemd/system/socks.service
    content: |
      [Unit]
      Description=SOCKS Proxy

      [Service]
      Restart=always
      User={{user}}
      ExecStart=/usr/bin/ssh {{user}}@localhost -N -n -D "*:{{port}}" -o StrictHostKeyChecking=no

      [Install]
      WantedBy=multi-user.target
- command: systemctl daemon-reload
- service: name='socks' enabled=yes state=restarted
